[package]
name = "petronel-graphql"
version = "0.1.0"
authors = ["Walfie <walfington@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.28"
chrono = { version = "0.4.11", features = ["serde"] }
dashmap = "3.11.1"
serde = { version = "1.0.107", features = ["derive"] }
serde_json = "1.0.52"
string_cache = "0.8.0"
tokio = { version = "0.2.20", features = ["macros"] }
once_cell = "1.3.1"
regex = "1.3.7"
