[package]
name = "petronel-graphql"
version = "0.1.0"
authors = ["Walfie <walfington@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.28"
chrono = { version = "0.4.11", features = ["serde"] }
dashmap = "4.0.0-rc2"
futures-util = "0.3.5"
hyper = "0.13.5"
hyper-tls = "0.4.1"
once_cell = "1.3.1"
regex = "1.3.7"
serde = { version = "1.0.107", features = ["derive"] }
serde_json = "1.0.52"
slog = "2.5.2"
slog-async = "2.5.0"
slog-json = "2.3.0"
slog-term = "2.5.0"
string_cache = "0.8.0"
structopt = "0.3.14"
thiserror = "1.0.16"
tokio = { version = "0.2.20", features = ["macros", "sync", "time"] }
tower = "0.3.1"
twitter-stream = "0.10.0-alpha.6"
ringbuf = "0.2.1"
